name: Generate 3D Contribution Graph

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate 3D Profile Contribution Graph
        uses: yoshi389111/github-profile-3d-contrib@main
        with:
          user: ${{ github.repository_owner }}
          output: output/profile-3d-contrib.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Push SVG to output branch
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add -f output
          git commit -m "Update 3D contrib graph" || exit 0
          git push origin HEAD:output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: always()
