name: Generate 3D Contribution Graph

on:
  schedule:
    # Runs every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Generate 3D Contrib
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Generate GitHub Profile 3D Contrib
        uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      - name: Push to Output Branch
        shell: bash
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "<>"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}.git
          git fetch origin output
          git checkout output || git checkout -b output
          if ls output/ 2>/dev/null | grep -q .; then
            git add output/
            if git diff --staged --quiet; then
              echo "No new changes"
            else
              git commit -m "Update 3D contrib SVG"
              git push origin output
            fi
          else
            echo "No files in output/, action failed to generate SVG"
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
